---

- name: Add container to dynamic inventory
  add_host:
    name: "{{ item.name }}"
    ansible_user: root
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    groups: 
      - lxd_containers
      - distccd
  delegate_to: localhost
  with_items: "{{ hostvars[thehost].lxd_containers }}"
  loop_control:
    label: "{{ item.name }}"

