---

- name: Add container to dynamic inventory
  add_host:
    name: "{{ item.name }}"
    ansible_user: root
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    groups: "{{ item.ansible_groups|default([]) + ['lxd_containers'] }}"
  delegate_to: localhost
  with_items: "{{ hostvars[thehost].lxd_containers }}"
  loop_control:
    label: "{{ item.name }}"

